"""llm providers

Revision ID: 061344287261
Revises: 7075df609915
Create Date: 2026-08-31 14:27:51.799801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '061344287261'
down_revision: Union[str, Sequence[str], None] = '7075df609915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('protocol', sa.String(length=16), nullable=False),
    sa.Column('base_url', sa.String(length=200), nullable=False),
    sa.Column('api_key', sa.String(length=400), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('vision_model', sa.String(length=64), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_llm_provider_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('llm_provider')
    # ### end Alembic commands ###
