"""baseline schema

Revision ID: 1f9b20bcf033
Revises: 
Create Date: 2026-08-31 13:36:25.038886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f9b20bcf033'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('tax_no', sa.String(length=32), nullable=False),
    sa.Column('taxpayer_type', sa.String(length=16), nullable=False),
    sa.Column('entity_type', sa.String(length=16), nullable=False),
    sa.Column('accounting_standard', sa.String(length=16), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('start_period', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('direction', sa.Integer(), nullable=False),
    sa.Column('parent_code', sa.String(length=32), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_leaf', sa.Boolean(), nullable=False),
    sa.Column('is_preset', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'code', name='uq_account_book_code')
    )
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_parent_code'), ['parent_code'], unique=False)

    op.create_table('ledger_period_balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('account_code', sa.String(length=32), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('opening_debit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('opening_credit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('period_debit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('period_credit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('closing_debit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('closing_credit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'account_code', 'period', name='uq_period_balance')
    )
    with op.batch_alter_table('ledger_period_balance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_period_balance_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_period_balance_period'), ['period'], unique=False)

    op.create_table('opening_balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('account_code', sa.String(length=32), nullable=False),
    sa.Column('debit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'account_code', name='uq_opening_book_code')
    )
    with op.batch_alter_table('opening_balance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opening_balance_book_id'), ['book_id'], unique=False)

    op.create_table('period_close',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('closed_by', sa.Integer(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['closed_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'period', name='uq_period_close')
    )
    with op.batch_alter_table('period_close', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_period_close_book_id'), ['book_id'], unique=False)

    op.create_table('report_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('report', sa.String(length=8), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('row_no', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=True),
    sa.Column('formula', sa.Text(), nullable=True),
    sa.Column('in_total', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'report', 'key', name='uq_report_template_row')
    )
    with op.batch_alter_table('report_template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_template_book_id'), ['book_id'], unique=False)

    op.create_table('voucher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=4), nullable=False),
    sa.Column('voucher_no', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('voucher_date', sa.Date(), nullable=False),
    sa.Column('attachment_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('total_debit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_credit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('carryover_type', sa.String(length=16), nullable=True),
    sa.Column('reverses_voucher_id', sa.Integer(), nullable=True),
    sa.Column('voided_by_voucher_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('audited_by', sa.Integer(), nullable=True),
    sa.Column('audited_at', sa.DateTime(), nullable=True),
    sa.Column('posted_by', sa.Integer(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['audited_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['posted_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reverses_voucher_id'], ['voucher.id'], ),
    sa.ForeignKeyConstraint(['voided_by_voucher_id'], ['voucher.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'period', 'voucher_no', name='uq_voucher_no')
    )
    with op.batch_alter_table('voucher', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voucher_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_voucher_period'), ['period'], unique=False)
        batch_op.create_index(batch_op.f('ix_voucher_status'), ['status'], unique=False)

    op.create_table('attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voucher_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=260), nullable=False),
    sa.Column('original_filename', sa.String(length=200), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['voucher_id'], ['voucher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachment_voucher_id'), ['voucher_id'], unique=False)

    op.create_table('voucher_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voucher_id', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('summary', sa.String(length=200), nullable=False),
    sa.Column('account_code', sa.String(length=32), nullable=False),
    sa.Column('debit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['voucher_id'], ['voucher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('voucher_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voucher_line_voucher_id'), ['voucher_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voucher_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voucher_line_voucher_id'))

    op.drop_table('voucher_line')
    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachment_voucher_id'))

    op.drop_table('attachment')
    with op.batch_alter_table('voucher', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voucher_status'))
        batch_op.drop_index(batch_op.f('ix_voucher_period'))
        batch_op.drop_index(batch_op.f('ix_voucher_book_id'))

    op.drop_table('voucher')
    with op.batch_alter_table('report_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_template_book_id'))

    op.drop_table('report_template')
    with op.batch_alter_table('period_close', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_period_close_book_id'))

    op.drop_table('period_close')
    with op.batch_alter_table('opening_balance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opening_balance_book_id'))

    op.drop_table('opening_balance')
    with op.batch_alter_table('ledger_period_balance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_period_balance_period'))
        batch_op.drop_index(batch_op.f('ix_ledger_period_balance_book_id'))

    op.drop_table('ledger_period_balance')
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_parent_code'))
        batch_op.drop_index(batch_op.f('ix_account_code'))
        batch_op.drop_index(batch_op.f('ix_account_book_id'))

    op.drop_table('account')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    op.drop_table('book')
    # ### end Alembic commands ###
