"""m5 invoices and tax params

Revision ID: 7075df609915
Revises: 1f9b20bcf033
Create Date: 2026-08-31 13:59:00.278703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7075df609915'
down_revision: Union[str, Sequence[str], None] = '1f9b20bcf033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_param',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('tax', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'tax', 'name', 'effective_from', name='uq_tax_param')
    )
    with op.batch_alter_table('tax_param', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tax_param_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_param_tax'), ['tax'], unique=False)

    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('invoice_type', sa.String(length=16), nullable=False),
    sa.Column('invoice_code', sa.String(length=32), nullable=True),
    sa.Column('invoice_no', sa.String(length=32), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('seller_name', sa.String(length=128), nullable=False),
    sa.Column('seller_tax_no', sa.String(length=32), nullable=False),
    sa.Column('buyer_name', sa.String(length=128), nullable=False),
    sa.Column('buyer_tax_no', sa.String(length=32), nullable=False),
    sa.Column('goods_name', sa.String(length=200), nullable=False),
    sa.Column('amount_excl', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('voucher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['voucher_id'], ['voucher.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'kind', 'invoice_no', name='uq_invoice_no')
    )
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_invoice_no'), ['invoice_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_kind'), ['kind'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_kind'))
        batch_op.drop_index(batch_op.f('ix_invoice_invoice_no'))
        batch_op.drop_index(batch_op.f('ix_invoice_book_id'))

    op.drop_table('invoice')
    with op.batch_alter_table('tax_param', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tax_param_tax'))
        batch_op.drop_index(batch_op.f('ix_tax_param_book_id'))

    op.drop_table('tax_param')
    # ### end Alembic commands ###
