"""ai docs

Revision ID: f2aa3a403b09
Revises: 061344287261
Create Date: 2026-08-31 16:17:29.464371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2aa3a403b09'
down_revision: Union[str, Sequence[str], None] = '061344287261'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_doc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=16), nullable=False),
    sa.Column('source_kind', sa.String(length=16), nullable=False),
    sa.Column('file_name', sa.String(length=200), nullable=False),
    sa.Column('staging_path', sa.String(length=300), nullable=False),
    sa.Column('fields_json', sa.Text(), nullable=False),
    sa.Column('warnings_json', sa.Text(), nullable=False),
    sa.Column('layers_json', sa.Text(), nullable=False),
    sa.Column('model_output', sa.Text(), nullable=False),
    sa.Column('voucher_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['voucher_id'], ['voucher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_doc', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_doc_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_doc_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_doc', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_doc_status'))
        batch_op.drop_index(batch_op.f('ix_ai_doc_book_id'))

    op.drop_table('ai_doc')
    # ### end Alembic commands ###
