"""资产负债表（会小企01表）与利润表（会小企02表）默认取数公式模板。

line 行公式：[[科目编码, 符号], ...]；资产侧按 net(d-c) 取值，负债权益侧按 net(c-d) 取值。
calc 行公式：["+key", "-key", ...]，按已计算行汇总。
成本类科目（4001/4101/4401/4403/4301）期末余额并入存货与其他流动资产，
保证 66 个科目全部被资产负债表覆盖，从而使「资产总计 = 负债和所有者权益总计」恒成立。
"""

BS_TEMPLATE: list[dict] = [
    {"key": "monetary_funds", "row_no": 1, "name": "货币资金", "kind": "line", "side": "debit",
     "formula": [["1001", 1], ["1002", 1], ["1012", 1]], "in_total": True},
    {"key": "short_investment", "row_no": 2, "name": "短期投资", "kind": "line", "side": "debit",
     "formula": [["1101", 1]], "in_total": True},
    {"key": "notes_receivable", "row_no": 3, "name": "应收票据", "kind": "line", "side": "debit",
     "formula": [["1121", 1]], "in_total": True},
    {"key": "accounts_receivable", "row_no": 4, "name": "应收账款", "kind": "line", "side": "debit",
     "formula": [["1122", 1]], "in_total": True},
    {"key": "prepayments", "row_no": 5, "name": "预付账款", "kind": "line", "side": "debit",
     "formula": [["1123", 1]], "in_total": True},
    {"key": "dividends_receivable", "row_no": 6, "name": "应收股利", "kind": "line", "side": "debit",
     "formula": [["1131", 1]], "in_total": True},
    {"key": "interest_receivable", "row_no": 7, "name": "应收利息", "kind": "line", "side": "debit",
     "formula": [["1132", 1]], "in_total": True},
    {"key": "other_receivables", "row_no": 8, "name": "其他应收款", "kind": "line", "side": "debit",
     "formula": [["1221", 1]], "in_total": True},
    {"key": "inventory", "row_no": 9, "name": "存货", "kind": "line", "side": "debit",
     "formula": [["1401", 1], ["1402", 1], ["1403", 1], ["1404", 1], ["1405", 1], ["1407", 1],
                 ["1408", 1], ["1411", 1], ["1421", 1], ["4001", 1], ["4101", 1], ["4401", 1],
                 ["4403", 1]], "in_total": True},
    {"key": "other_current_assets", "row_no": 10, "name": "其他流动资产", "kind": "line", "side": "debit",
     "formula": [["1901", 1], ["4301", 1]], "in_total": True},
    {"key": "total_current_assets", "row_no": 11, "name": "流动资产合计", "kind": "calc", "side": None,
     "formula": ["+monetary_funds", "+short_investment", "+notes_receivable", "+accounts_receivable",
                 "+prepayments", "+dividends_receivable", "+interest_receivable", "+other_receivables",
                 "+inventory", "+other_current_assets"], "in_total": True},
    {"key": "long_term_bond_investments", "row_no": 12, "name": "长期债券投资", "kind": "line",
     "side": "debit", "formula": [["1501", 1]], "in_total": True},
    {"key": "long_term_equity_investments", "row_no": 13, "name": "长期股权投资", "kind": "line",
     "side": "debit", "formula": [["1511", 1]], "in_total": True},
    {"key": "fixed_asset_origin", "row_no": 14, "name": "固定资产原价", "kind": "line", "side": "debit",
     "formula": [["1601", 1]], "in_total": False},
    {"key": "less_accumulated_depreciation", "row_no": 15, "name": "减：累计折旧", "kind": "line",
     "side": "debit", "formula": [["1602", -1]], "in_total": False},
    {"key": "fixed_asset_net", "row_no": 16, "name": "固定资产账面价值", "kind": "calc", "side": None,
     "formula": ["+fixed_asset_origin", "-less_accumulated_depreciation"], "in_total": True},
    {"key": "construction_in_progress", "row_no": 17, "name": "在建工程", "kind": "line", "side": "debit",
     "formula": [["1604", 1]], "in_total": True},
    {"key": "construction_materials", "row_no": 18, "name": "工程物资", "kind": "line", "side": "debit",
     "formula": [["1605", 1]], "in_total": True},
    {"key": "fixed_assets_disposal", "row_no": 19, "name": "固定资产清理", "kind": "line", "side": "debit",
     "formula": [["1606", 1]], "in_total": True},
    {"key": "productive_biological_assets", "row_no": 20, "name": "生产性生物资产", "kind": "line",
     "side": "debit", "formula": [["1621", 1], ["1622", 1]], "in_total": True},
    {"key": "intangible_assets", "row_no": 21, "name": "无形资产", "kind": "line", "side": "debit",
     "formula": [["1701", 1], ["1702", 1]], "in_total": True},
    {"key": "long_term_deferred_expenses", "row_no": 22, "name": "长期待摊费用", "kind": "line",
     "side": "debit", "formula": [["1801", 1]], "in_total": True},
    {"key": "other_noncurrent_assets", "row_no": 23, "name": "其他非流动资产", "kind": "line",
     "side": "debit", "formula": [], "in_total": True},
    {"key": "total_noncurrent_assets", "row_no": 24, "name": "非流动资产合计", "kind": "calc", "side": None,
     "formula": ["+long_term_bond_investments", "+long_term_equity_investments", "+fixed_asset_net",
                 "+construction_in_progress", "+construction_materials", "+fixed_assets_disposal",
                 "+productive_biological_assets", "+intangible_assets", "+long_term_deferred_expenses",
                 "+other_noncurrent_assets"], "in_total": True},
    {"key": "total_assets", "row_no": 25, "name": "资产总计", "kind": "calc", "side": None,
     "formula": ["+total_current_assets", "+total_noncurrent_assets"], "in_total": False},
    {"key": "short_term_loans", "row_no": 26, "name": "短期借款", "kind": "line", "side": "credit",
     "formula": [["2001", 1]], "in_total": True},
    {"key": "notes_payable", "row_no": 27, "name": "应付票据", "kind": "line", "side": "credit",
     "formula": [["2201", 1]], "in_total": True},
    {"key": "accounts_payable", "row_no": 28, "name": "应付账款", "kind": "line", "side": "credit",
     "formula": [["2202", 1]], "in_total": True},
    {"key": "advances_from_customers", "row_no": 29, "name": "预收账款", "kind": "line", "side": "credit",
     "formula": [["2203", 1]], "in_total": True},
    {"key": "employee_compensation_payable", "row_no": 30, "name": "应付职工薪酬", "kind": "line",
     "side": "credit", "formula": [["2211", 1]], "in_total": True},
    {"key": "taxes_payable", "row_no": 31, "name": "应交税费", "kind": "line", "side": "credit",
     "formula": [["2221", 1]], "in_total": True},
    {"key": "interest_payable", "row_no": 32, "name": "应付利息", "kind": "line", "side": "credit",
     "formula": [["2231", 1]], "in_total": True},
    {"key": "profit_payable", "row_no": 33, "name": "应付利润", "kind": "line", "side": "credit",
     "formula": [["2232", 1]], "in_total": True},
    {"key": "other_payables", "row_no": 34, "name": "其他应付款", "kind": "line", "side": "credit",
     "formula": [["2241", 1]], "in_total": True},
    {"key": "other_current_liabilities", "row_no": 35, "name": "其他流动负债", "kind": "line",
     "side": "credit", "formula": [], "in_total": True},
    {"key": "total_current_liabilities", "row_no": 36, "name": "流动负债合计", "kind": "calc", "side": None,
     "formula": ["+short_term_loans", "+notes_payable", "+accounts_payable", "+advances_from_customers",
                 "+employee_compensation_payable", "+taxes_payable", "+interest_payable",
                 "+profit_payable", "+other_payables", "+other_current_liabilities"], "in_total": True},
    {"key": "long_term_loans", "row_no": 37, "name": "长期借款", "kind": "line", "side": "credit",
     "formula": [["2501", 1]], "in_total": True},
    {"key": "long_term_payables", "row_no": 38, "name": "长期应付款", "kind": "line", "side": "credit",
     "formula": [["2701", 1]], "in_total": True},
    {"key": "deferred_income", "row_no": 39, "name": "递延收益", "kind": "line", "side": "credit",
     "formula": [["2401", 1]], "in_total": True},
    {"key": "other_noncurrent_liabilities", "row_no": 40, "name": "其他非流动负债", "kind": "line",
     "side": "credit", "formula": [], "in_total": True},
    {"key": "total_noncurrent_liabilities", "row_no": 41, "name": "非流动负债合计", "kind": "calc",
     "side": None,
     "formula": ["+long_term_loans", "+long_term_payables", "+deferred_income",
                 "+other_noncurrent_liabilities"], "in_total": True},
    {"key": "total_liabilities", "row_no": 42, "name": "负债合计", "kind": "calc", "side": None,
     "formula": ["+total_current_liabilities", "+total_noncurrent_liabilities"], "in_total": True},
    {"key": "paid_in_capital", "row_no": 43, "name": "实收资本", "kind": "line", "side": "credit",
     "formula": [["3001", 1]], "in_total": True},
    {"key": "capital_reserve", "row_no": 44, "name": "资本公积", "kind": "line", "side": "credit",
     "formula": [["3002", 1]], "in_total": True},
    {"key": "surplus_reserve", "row_no": 45, "name": "盈余公积", "kind": "line", "side": "credit",
     "formula": [["3101", 1]], "in_total": True},
    {"key": "undistributed_profits", "row_no": 46, "name": "未分配利润", "kind": "line", "side": "credit",
     "formula": [["3103", 1], ["3104", 1], ["5001", 1], ["5051", 1], ["5111", 1], ["5301", 1],
                 ["5401", 1], ["5402", 1], ["5403", 1], ["5601", 1], ["5602", 1], ["5603", 1],
                 ["5711", 1], ["5801", 1]], "in_total": True},
    {"key": "total_owners_equity", "row_no": 47, "name": "所有者权益合计", "kind": "calc", "side": None,
     "formula": ["+paid_in_capital", "+capital_reserve", "+surplus_reserve", "+undistributed_profits"],
     "in_total": True},
    {"key": "total_liabilities_and_equity", "row_no": 48, "name": "负债和所有者权益总计", "kind": "calc",
     "side": None, "formula": ["+total_liabilities", "+total_owners_equity"], "in_total": False},
]

IS_TEMPLATE: list[dict] = [
    {"key": "operating_revenue", "row_no": 1, "name": "一、营业收入", "kind": "line", "side": "credit",
     "formula": [["5001", 1], ["5051", 1]]},
    {"key": "operating_cost", "row_no": 2, "name": "减：营业成本", "kind": "line", "side": "debit",
     "formula": [["5401", 1], ["5402", 1]]},
    {"key": "business_taxes", "row_no": 3, "name": "税金及附加", "kind": "line", "side": "debit",
     "formula": [["5403", 1]]},
    {"key": "selling_expenses", "row_no": 4, "name": "销售费用", "kind": "line", "side": "debit",
     "formula": [["5601", 1]]},
    {"key": "administrative_expenses", "row_no": 5, "name": "管理费用", "kind": "line", "side": "debit",
     "formula": [["5602", 1]]},
    {"key": "financial_expenses", "row_no": 6, "name": "财务费用", "kind": "line", "side": "debit",
     "formula": [["5603", 1]]},
    {"key": "investment_income", "row_no": 7, "name": "加：投资收益", "kind": "line", "side": "credit",
     "formula": [["5111", 1]]},
    {"key": "operating_profit", "row_no": 8, "name": "二、营业利润", "kind": "calc", "side": None,
     "formula": ["+operating_revenue", "-operating_cost", "-business_taxes", "-selling_expenses",
                 "-administrative_expenses", "-financial_expenses", "+investment_income"]},
    {"key": "nonoperating_income", "row_no": 9, "name": "加：营业外收入", "kind": "line", "side": "credit",
     "formula": [["5301", 1]]},
    {"key": "nonoperating_expenses", "row_no": 10, "name": "减：营业外支出", "kind": "line",
     "side": "debit", "formula": [["5711", 1]]},
    {"key": "total_profit", "row_no": 11, "name": "三、利润总额", "kind": "calc", "side": None,
     "formula": ["+operating_profit", "+nonoperating_income", "-nonoperating_expenses"]},
    {"key": "income_tax_expense", "row_no": 12, "name": "减：所得税费用", "kind": "line", "side": "debit",
     "formula": [["5801", 1]]},
    {"key": "net_profit", "row_no": 13, "name": "四、净利润", "kind": "calc", "side": None,
     "formula": ["+total_profit", "-income_tax_expense"]},
]


def seed_report_templates(db, book_id: int) -> None:
    import json

    from app.models.report import ReportTemplate

    for report, rows in (("bs", BS_TEMPLATE), ("is", IS_TEMPLATE)):
        for row in rows:
            db.add(
                ReportTemplate(
                    book_id=book_id,
                    report=report,
                    key=row["key"],
                    row_no=row["row_no"],
                    name=row["name"],
                    kind=row["kind"],
                    side=row["side"],
                    formula=json.dumps(row["formula"], ensure_ascii=False),
                    in_total=row.get("in_total", True),
                )
            )
    db.commit()
